server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: LinkGenerationService
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/urls
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
