spring:
  application:
    name: LinkRedirectionService

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/urls
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8000